Repository javierbrea/npm-file-link, pull requests merged in 2019-11, with the labels that each got.

#5 V1.1.0
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  sonar-project.properties
Labels: dependencies

#6 V1.1.1
  .travis.yml
  CHANGELOG.md
  LICENSE
  NOTICE
  bin/npm-file-link
  package-lock.json
  package.json
  sonar-project.properties
  src/check.js
  src/command.js
  src/inquire.js
  src/link.js
  src/npm.js
  src/unlink.js
  src/utils/helpers.js
  src/utils/packages.js
  src/utils/paths.js
  test/check.spec.js
  test/command.spec.js
  test/index.spec.js
  test/inquire.spec.js
  test/link.spec.js
  test/npm.spec.js
  test/unlink.spec.js
  test/utils/helpers.spec.js
  test/utils/packages.spec.js
  test/utils/paths.spec.js
Labels: documentation

#7 Fix: Add commander to dependencies
  .travis.yml
  CHANGELOG.md
  package-lock.json
  package.json
  sonar-project.properties
Labels: bug

#8 uncomment sonar
  .travis.yml
Labels: bug
